### ISSUE TITLE
deprecate bin/build_demo.sh

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#185]
build_demo.sh was introduced because older versions of wombat-cli attempted to rebuild the .lock and .json on every `wombat deploy`. BJC now runs on latest wombat, which means `wombat deploy <AWESOME-STACK-NAME>` only launches the stack. Update tasks were moved to `wombat update`. This way the user workflow, without leaving the cli, becomes:

```
wombat deploy OMG-STACK
#launches the stack

wombat outputs OMG-STACK
#shows you the outputs, eg Workstation IPs

wombat delete OMG-STACK
#deletes the stack
```

**Comment by scarolan** [comment]
Closing this since it requires upstream changes.  build_demo.sh works fine for those of us who are using it and are comfortable with it.  There's always the GUI for everyone else.  Wombat does enough already.  We don't need it to launch custom CF stacks too.
