### ISSUE TITLE
bjc_bass could use a pin to audit >= 2.0.0

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#219]
this would unblock using the audit cookbook as a handler, not having to worry about order of execution

this would require reformatting the profiles attribute to an array of hashes and setting the fetcher attribute to `chef-server` as per https://vjeffrey.github.io/#fetcher-attribute

**Comment by scarolan** [comment]
It's already pinned to 2.3.2.  I fixed the attributes and it seems to work ok now.
