### ISSUE TITLE
Refactor IAM role

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#225]
we have a role `testKitchenAndKnifeEc2` hardcoded. Our readme should explain what this role is for and how to create it. This is missing for when we share the json and AMIs with other teams (eg training).

**Comment by scarolan** [comment]
What we need to do is find out what 'minimum viable IAM' role is for a partner to be able to run the demo, and then publish that for them.  Or even better, have the CF template itself spin up at temporary IAM role, thus granting itself the required permissions to run.

**Comment by scarolan** [comment]
I want to rename this IAM role as `chefDemo` and grant it only the minimum perms necessary to get through a demo and spin up TK instances inside it.
