### ISSUE TITLE
Update audit cookbook config and chef-server.rb to proxy data through chef server

### ISSUE THREAD

**Issue by smford22** [chef-cft/bjc#237]
https://github.com/jeremymv2/compliance_demo_officehour#no-more-data_collector-in-clientrb

Audit cookbook needs...
```
# wrapper cookbook
default['audit']['collector'] = 'chef-server-visibility'
default['audit']['profiles'] = [
  {
    'name' => 'linux',
    'compliance' => 'jmiller/linux'
  }
]
```
Chef server needs...

```
# chef-server.rb
data_collector['root_url'] = 'https://automate-server.test/data-collector/v0/'
data_collector['token'] = 'TOKEN'
```

**Comment by scarolan** [comment]
Can't compliance data simply be sent directly from the Chef server now?  Are we on a new emough version to do that?

**Comment by scarolan** [comment]
I'm going to close this.  We're already sending data direction into automate via the data_collector and it's working fine.
