### ISSUE TITLE
Deploys don't show up in trend graph.

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#374]
Unsure of exact version, but suspect this happened when runners were officially launched. Suspicion is that this will be fixed upstream if this issue is closed in wombat: https://github.com/chef-cft/wombat/issues/249#issuecomment-270789545

Will see if I can't validate in the meantime.

**Comment by scarolan** [comment]
I believe these are working now.  Let's make sure someone else confirms and we can close this.

**Comment by scarolan** [comment]
Verified deploy marker now shows up for changes.
