### ISSUE TITLE
Refactor Start_Demo.ps1 into Ruby (Chef?)

### ISSUE THREAD

**Issue by scarolan** [chef-cft/bjc#384]
This script is janky.  Let's transform it into a chef solo friendly recipe.

**Comment by smacfarlane** [comment]
@scarolan  Looking at what this script does, I think native powershell is the right language  to use.   I'll take a pass at it and see if can make  some less-janky powershell.

**Comment by scarolan** [comment]
I think you're right!  Most of what's in there is just simple native powershell.  Converting it all to chef would just end up with a bunch of execute statements.  The updating of the .kitchen.yml was what felt kind of weird to me - perl search and replace is very 1980s way of doing it.
