### ISSUE TITLE
Evaluate SSL scanner on windows

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#385]
High level: Spin up a fourthcoffee instance, then run the SSL scan profile. How does it look ootb? How easy is it to remediate.

Might be as simple as a registry key, and if so, easy win. Will investigate further as time allows.

Ref: https://www.digicert.com/ssl-support/iis-disabling-ssl-v3.htm

**Comment by scarolan** [comment]
I have a prototype cookbook that enables exactly this.  http://github.com/scarolan/my_fourthcoffee
