### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#391]
Separating this from issue 364, as that lays out some good feature enhancement work that I wouldn't want this getting confused with. I'm using this issue to collect some low-level fixes/changes that the README, CONTRIBUTE, and SSL_Demo_Script documents can use to better capture recent changes/updates to the project.

**Comment by ChefRycar** [comment]
CONTRIBUTE.md:

- Refers to key setup instructions "at the top of the page" which is actually now in a separate document.
- The copy/pasteable bits to copy keys into your project don't quite work. Places them in a keys/ directory wheras the build scripts expect them to be loose in the respective parent directories. The keys/ directory also isn't captured by the .gitignore, so creates some unexpected noise when committing. (NOTE: Fix may just be to clean up the tarball or scripts, and leave the readme itself alone. Will create separate issue if so.)
- Looks like there may be some duplicate data in README.md and CONTRIBUTE.md. Consolidate before they have a chance to get out of sync!

SSL_Demo_Script:

- Add a section summarizing the personas available in workflow.

README.md: 

- Update references to our internal slack channels to make more partner/OSS friendly.

**Comment by ChefRycar** [comment]
CONTRIBUTE/README.md: Wrong filename for zst file backup. Says chef-demo-backup, should be chef-automate-backup

**Comment by ChefRycar** [comment]
CONTRIBUTE/README.md: Doesn't call out need to update checksum in the bjc_automate cookbook when updating the backup file.

**Comment by scarolan** [comment]
Regarding the keys file, i think someone changed the keys.tar.gz file.  The copy-pasta bash snippet used to work just fine.

**Comment by scarolan** [comment]
Ok, I think i fixed all the other issues in PR #413
