### ISSUE TITLE
reaper bot notifications tuneup

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#404]
i think we're generally happy with the reaper's performance. It's a little chatty in the slack notifications though. I propose we configure it to notify only when it tried to reap and failed. This will make the notification actionable.

**Comment by scarolan** [comment]
/me puts on his robe and wizard hat

**Comment by scarolan** [comment]
Reaper bot was adjusted to only notify when stacks cannot be deleted.  We should see a notification tonight for a stack i created that has an orphaned test kitchen instance in it.

**Comment by binamov** [comment]
what's the actionable protocol? do we have to ping the stack owner? do we delete it ourselves?

**Comment by scarolan** [comment]
You can do one of a few things:
1.  Ping the owner and tell them to delete their stack.
2.  Delete it yourself
3.  Wait until midnight when the test kitchen reaper will kill the orphaned TK instance, allowing the 1am demo reaper to kill the stack.
