### ISSUE TITLE
Remove or comment lines for Windows Test Kitchen

### ISSUE THREAD

**Issue by nweddle** [chef-cft/bjc#409]
Currently, windows_user_data for kitchen_windows.yml.erb will happily change our Administrator password out from under us while running Windows Test Kitchen. Will need to either comment out the following lines or remove them.

https://github.com/chef-cft/bjc/blob/43cecc2ed66c064bdb139b9b38fec09a8d95912d/cookbooks/bjc_workstation/files/default/windows_user_data#L5-L7

**Comment by scarolan** [comment]
Is that a bad thing?  I kind of figured the user would *want* the ability to set their own password in TK.  Or do we want to just let test kitchen generate some random password.
