### ISSUE TITLE
Nodes should run chef-client daemonized

### ISSUE THREAD

**Issue by mattray** [chef-cft/bjc#421]
There would be more UI data in Automate if nodes checked in periodically (15 minutes?), enhancing the demonstration.

**Comment by binamov** [comment]
chef-client as a daemon slows down the already _watching paint dry_ pipeline. Automate's Workflow uses push-jobs for deployments and every time push-jobs hits a chef-client that's already running (eg a daemon triggered run) it will wait a bit and eventually time out. 

If what we really want to solve for is more data, there may be other ways to produce some e.g. as part of `start me up.ps1`.

**Comment by scarolan** [comment]
Agree with Bakh here.  Let's either add a second script or more chef client runs in the start_demo.ps1 script.

**Comment by binamov** [comment]
Marking this as Wontfix and closing. Please see https://github.com/chef-cft/bjc/issues/424
