### ISSUE TITLE
Moar data in Automate dashboards

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#424]
one way to solve for this is to add a few more runs to the `start me up.ps1`, another may be to add a similar script whose job is to only push jobs a few runs. An operator could run this script separately, if so needed. Solving this with `chef-client` as a daemon is not ideal as per https://github.com/chef-cft/bjc/issues/421#issuecomment-283487550

**Comment by binamov** [comment]
from @gmiranda23 
generate more interesting looking data for your demos:
```while($true) { knife job start chef-client -s *:*; sleep $(Get-Random -Maximum 240 -Minimum 60)}```


3 replies
Bakh Inamov
[5 minutes ago] 
should we just have this run at the end of start-me-up script until the operator closes the window?

George Miranda
[2 minutes ago] 
maybe.  as long as something gets echo’ed out so folks know it’ll keep running/generating data until they close it.

Bakh Inamov
[1 minute ago] 
or maybe a *moar data* shortcut icon on the desktop instead

**Comment by scarolan** [comment]
The new startup script solves for this and begins populating data with chef runs immediately after startup tasks are done.
