### ISSUE TITLE
Delivered stage fails if acceptance-bjc-demo-#{stack}.json does not exist

### ISSUE THREAD

**Issue by scarolan** [chef-cft/bjc#446]
This is an edge case, here's how it happens:

New runner node, has never run a build before.  /var/opt/delivery/workspace/stacks does not exist yet.

The deploy phase in delivered will fail because it cannot find these files.

**Comment by scarolan** [comment]
Or to be more correct, there is no JSON file in S3 yet to populate this template :

source 'https://s3-us-west-2.amazonaws.com/bjcpublic/acceptance-bjc-demo-#{cloud}.json'

**Comment by binamov** [comment]
pretty sure this works now
