### ISSUE TITLE
Add a cloud toggle to build_demo.sh

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#471]
With the addition of azure builds, our pipeline now spits out a pair of cloud-specific configs. This breaks the behavior of build_demo.sh, as it is unfamiliar with the new naming convention in >2.0. 

Intend to add a cloud toggle, that will default to the original naming convention if not set to preserve backwards compatibility.

This should pave the way for the work in https://github.com/chef-cft/bjc/issues/465
As toggle can be used as a conditional for further build customizations.

**Comment by ChefRycar** [comment]
Smelled a half-baked idea early enough. The script is aws-specific enough at present that there's little point in being clever. Gonna just whip up a new script for the >2.0 naming convention, and leave the existing script alone for the time being. 7AM decisions for the win.

**Comment by russellseymour** [comment]
@ChefRycar Have a look at the `build_demo.sh` script in my branch `russellseymour/azure-demo` as I updated it a lot yesterday to handle AWS and Azure
