### ISSUE TITLE
code/atom aliases missing in cmdr post 2.0.0

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#473]
Likely related to the switch from the Administrator user to the chef user. Haven't dug further yet, but wanted to track.

**Comment by SteveDelFante** [comment]
I also need the atom alias put back in for the chef user in the ChefDK PowerShell. The workflow training materials need this please.

**Comment by ChefRycar** [comment]
Not sure why we didn't need to do this for Administrator, but easiest thing is likely to figure out the path to each executable, and just update the $PATH in the bjc_workstation cookbook or start_me_up script.

**Comment by binamov** [comment]
fixed in #503
