### ISSUE TITLE
Chrome auto-updates, breaking all SSL

### ISSUE THREAD

**Issue by scarolan** [chef-cft/bjc#499]
Here's the registry bit we need to flip to stop this annoying behavior

Set the value of HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update\AutoUpdateCheckPeriodMinutes to the REG_DWORD value of "0".

**Comment by binamov** [comment]
we've had this reg key in for a while now

the other one that may help is https://www.chromium.org/administrators/policy-list-3#EnableCommonNameFallbackForLocalAnchors

it seems Chrome respects reg keys only if the machine is domain-joined 🤕
