### ISSUE TITLE
Certs in ~/.chef/trusted_certs on workstation are invalid

### ISSUE THREAD

**Issue by scarolan** [chef-cft/bjc#514]
This causes the startup script to fail.  Whatever is generating these SSL certs needs to be fixed, or we need to replace it with a 'knife ssl fetch' in the startup script.

**Comment by scarolan** [comment]
Workaround for now:

run `knife ssl fetch`
re-run ~/Start_Demo.ps1

**Comment by binamov** [comment]
pretty sure it's related to our refactor of that knife.rb template

**Comment by binamov** [comment]
fixed in https://github.com/chef-cft/wombat/pull/335
