### ISSUE TITLE
Changing source AMIs doesn't trigger new build

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#536]
The build_cookbook's "publish.rb" conditionally runs only if "changed_cookbooks" is true, so does not pick up edge cases like if the source amis change in wombat.yml.

What would folks think if we used the presence of a new version number in wombat.yml as a "force build" parameter? It should be incremented with each build anyway, since it's already a condition for generating a unique json name

**Comment by scarolan** [comment]
+1 to the force build parameter.  incrementing cookbooks feels kind of janky
