### ISSUE TITLE
Automate 0.8.5 compliance beta requires audit cookbook >= 4.0

### ISSUE THREAD

**Issue by smacfarlane** [chef-cft/bjc#548]
If the compliance beta feature is enabled, no data will appear under the compliance tab unless 

* audit cookbook >= 4.0
* inspec gem >= 1.24.0

and the following node attributes are changed in bjc_bass:

default['audit']['collector'] = 'chef-compliance'

should be: 

default['audit']['reporter'] = 'chef-server-automate'

**Comment by SteveDelFante** [comment]
I would like the above to be part of BJC so we won't need to make these changes each time we regen the AMIs.

**Comment by ChefRycar** [comment]
For reference, there was a version pinning due to a problem we uncovered when using later versions of inspec, where it wasn't properly identifying ssl ports after we updated ciphers (see: https://github.com/dev-sec/ssl-baseline/issues/12). We'll need to make sure our audits are behaving as expected after updating those values.

**Comment by smacfarlane** [comment]
Inspec 1.24.0 reported the results correctly when I tested it.  However, my primary focus was on presence of data so a second set of eyes to validate would be good.

**Comment by binamov** [comment]
should be fixed here https://github.com/chef-cft/bjc/pull/551

**Comment by binamov** [comment]
bjc 2.2.1 in acceptance:

```
> knife cookbook show audit
audit   4.0.0
```

```
ubuntu@union:~$ /opt/chef/embedded/bin/inspec -v
1.27.0
```
![RDCMan_2017-06-13_19-34-54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53acb3447953d2fd0f7210af/125516c66e82c728ace21e0d46dab0b90e838d96ddb9ee14e90da6d9781518227049f07f3dd0b76af3006b1300051bff054a5556f9fed82ea6e26971885a09b8d56a5d7cc63d13febed74bb913a632c91edbe2e3d7158abd7f37ed998c4d341f01118efb5d32a79a4bce58f059ac.png)
