### ISSUE TITLE
Windows Workstation isn't bootstrapped nor connected in Compliance anymore

### ISSUE THREAD

**Issue by ffpollock** [chef-cft/bjc#552]
Likely the credential changes we did?

**Comment by scarolan** [comment]
Yes, when things were re-keyed and re-credentialed this stopped working.  It's not too hard to delete and re-add it though.  If you want to demo windows stuff i recommend taking the my_fourthcoffee repo for a spin.

**Comment by scarolan** [comment]
The easy fix for this is to change the username to `chef`in the compliance UI.  Alternatively someone could snap a new backup of compliance with the correct username in place.

**Comment by scarolan** [comment]
Since the stand-alone compliance server will be deprecated soon, i'm going to close this.  There are easier ways to demo Inspec and Compliance now that do not require the old GUI
