### ISSUE TITLE
upload planetexpress-ssl to automate and take another backup

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#564]
this would involve changing `bjc_bass` cookbook audit attributes to point at automate for its profile

**Comment by scarolan** [comment]
What is this for?  Are we creating a new cookbook called `planetexpress-ssl`?

**Comment by ChefRycar** [comment]
LttP on this thread, but planetexpress-ssl was created to account for a bug in the ssl resource that doesn't appear to properly detect our fix (when ssl is properly configured, it just returns no data for any check). As a stopgap I created a simplified ssl checker that uses commandline verifiers instead.
