### ISSUE TITLE
Move inspec profiles to root of project

### ISSUE THREAD

**Issue by smacfarlane** [chef-cft/bjc#618]
Currently, the inspec profiles that wrap the dev-sec/hardening profiles live in a tarball in the workstation cookbooks files directory.

These should be extracted and moved to the root of the project under /profiles,  and some tooling added to generate the tarball when updates are made.

This will allow new contributors to easily find and make changes to the profiles and add additional profiles.

**Comment by ChefRycar** [comment]
Targeting this with release 4.1.0, to include version pinnings as well.
