### ISSUE TITLE
DCA issue hardening recipe not remediating fully. fails one control

### ISSUE THREAD

**Issue by eluna2007** [chef-cft/bjc#625]
Similar to the old issue but now its failing on group assignment for /var/log
 directory '/var/log' do 
    owner 'root'
    group 'syslog'
  end

**Comment by ChefRycar** [comment]
This now also includes log configurations for auditd. Will be updating the wrapper cookbook to address, and add version pinnings to inspec profile to ensure we don't get hit by similar in future.
