### ISSUE TITLE
upgrade to current ec2 instances

### ISSUE THREAD

**Issue by ericcalabretta** [chef-cft/bjc#632]
Upgrade M3 instances to M5 & C3 instances to C5 instances. New instances are significantly cheaper also a little faster.

**Comment by ChefRycar** [comment]
Did some testing, and unfortunately there are a couple of blockers for m5/c5:
- Not currently available in all regions (asiapac in specific has no regions with *5 support yet)
- Requires some extra network configuration before use, even in supported regions.

That said, I'm happy to report that m4/c4 work just fine, and should give us at least some of the performance increase and cost savings laid out. Plan is to cut a release using these instance types, and create a blocked backlog issue for a future upgrade to m5/c5 pending availability in all regions.

**Comment by smacfarlane** [comment]
CloudFormation templates were updated in #635 to use M4/C4.
