### ISSUE TITLE
Speed up DCA launch

### ISSUE THREAD

**Issue by ChefRycar** [chef-cft/bjc#634]
DCA launch is currently quite slow. Propose some changes to speed things up and require less lead time for demos.

- Make initial test kitchen warm opt-in. Right now DCA automatically spins up a TK instance that's not used in the vanilla demo. Commenting out so that time is only spent if an SA requires TK

- Make use of powershell workflows to parallelize a lot of the "foreach" blocks. The script configures ecomacceptance on build nodes, and re-bootstraps the fleet. Parallelizing this should cut down launch time significantly.

**Comment by smacfarlane** [comment]
@ChefRycar  This looks like it was resolved in #635.  I'm going to mark this as complete. Please re-open if I'm in error.
