### ISSUE TITLE
include all cookbooks on workstation

### ISSUE THREAD

**Issue by ericcalabretta** [chef-cft/bjc#643]
include cookbooks on BJC workstation so we can show to customers or customize if needed.

dca_audit_baseline
dca_hardening_linux
dca_hardening_windows

**Comment by ChefRycar** [comment]
Updated with audit_baseline and hardening_linux. Hardening_windows needs some added development before it's usable (currently will lock you out of winrm if used), but will update it as well once it's ready to launch.

**Comment by smacfarlane** [comment]
Closed by #644 #646
